SPOTeam/Server

build.gradle, src/main/java/com/example/SwaggerConfig.java, src/main/java/com/example/spot/controller/MemberController.java, src/main/java/com/example/spot/controller/NotificationController.java, src/main/java/com/example/spot/controller/PostController.java, src/main/java/com/example/spot/controller/SearchController.java, src/main/java/com/example/spot/controller/SignInController.java, src/main/java/com/example/spot/controller/StudyController.java
> ex) #8 
<br/>
- Swagger Dependency 설정 (Spring 3.xx 버전에서 충돌이 발생하지 않는 springdoc-openapi-starter-webmvc-ui:2.0.4 사용)
- Swagger Config 파일 생성
<br/>
<br/>
Config 파일에 더 추가하면 좋을 사항이 있다면 코멘트로 알려주세요!
=> [CHORE] Add Swagger Dependency and Config

src/main/java/com/example/spot/domain/study/StudyPostComment.java
[>#이슈 번호, #이슈 링크 ] (https://github.com/SPOTeam/Server/issues/19)
<br/>
> StudyPostComment 엔티티에 대댓글 관련 컬럼 추가
<br/>
=> [modify] StudyPostComment 엔티티에 대댓글 관련 컬럼 추가

src/main/java/com/example/spot/domain/enums/ApplicationStatus.java, src/main/java/com/example/spot/domain/mapping/MemberStudy.java, src/main/java/com/example/spot/web/controller/MemberStudyController.java, src/main/java/com/example/spot/web/controller/StudyController.java
- #20 
<br/>
- 내 스터디 관련 API 구현
- 스터디 생성/참여 관련 API 구현
<br/>
X
<br/>
혹시 요청 URI 잘못된 거 있으면 알려주세요..!
=> [docs] Swagger 스터디 관련 기능 API 명세서 작성

src/main/java/com/example/spot/domain/Member.java, src/main/java/com/example/spot/domain/study/Study.java
- #27 
<br/>
- Member : isAdmin 추가
- Study : hitNum 추가
<br/>
X
<br/>
X
=> [modify] Add Attributes of Member and Study

src/main/java/com/example/spot/api/exception/handler/MemberHandler.java, src/main/java/com/example/spot/api/exception/handler/NotificationHandler.java, src/main/java/com/example/spot/api/exception/handler/PostHandler.java, src/main/java/com/example/spot/api/exception/handler/StudyHandler.java
> https://github.com/SPOTeam/Server/issues/31
<br/>
> 핸들러 뼈대 코드 생성
<br/>
=> [feat] 에러 핸들러 뼈대 코드 생성

src/main/java/com/example/spot/api/code/status/ErrorStatus.java, src/main/java/com/example/spot/api/code/status/SuccessStatus.java, src/main/java/com/example/spot/domain/mapping/PreferredStudy.java, src/main/java/com/example/spot/domain/study/Study.java, src/main/java/com/example/spot/repository/MemberStudyRepository.java, src/main/java/com/example/spot/repository/RegionRepository.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java, src/main/java/com/example/spot/service/notification/NotificationCommandService.java, src/main/java/com/example/spot/service/notification/NotificationCommandServiceImpl.java, src/main/java/com/example/spot/service/notification/NotificationQueryService.java, src/main/java/com/example/spot/service/notification/NotificationQueryServiceImpl.java, src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java, src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java, src/main/java/com/example/spot/web/controller/NotificationController.java, src/main/java/com/example/spot/web/controller/StudyController.java, src/main/java/com/example/spot/web/dto/study/request/StudyRegisterRequestDTO.java
> #이슈 링크 https://github.com/SPOTeam/Server/issues/52
<br/>
> 
프론트 API 호출 위해 코드 리팩토링 
1. Validation 추가
2. 엣지 케이스 에러 핸들링
3. 테스팅 통한 코드 리팩토링
=> [REFACTOR] 조회 및 스터디 API 코드 리팩토링

build.gradle, src/main/java/com/example/spot/api/code/status/ErrorStatus.java, src/main/java/com/example/spot/api/exception/handler/S3Handler.java, src/main/java/com/example/spot/config/S3Config.java, src/main/java/com/example/spot/service/s3/S3ImageService.java
- #53 
<br/>
- S3 Dependency
- S3 Config
- S3 Service
- TestController는 추후 삭제 예정입니다!
<br/>
> 
<br/>
=> [feat] S3 서비스 세팅

src/main/java/com/example/spot/api/code/status/SuccessStatus.java, src/main/java/com/example/spot/domain/Member.java, src/main/java/com/example/spot/repository/MemberStudyRepository.java, src/main/java/com/example/spot/repository/MemberThemeRepository.java, src/main/java/com/example/spot/repository/PreferredRegionRepository.java, src/main/java/com/example/spot/service/member/MemberService.java, src/main/java/com/example/spot/service/member/MemberServiceImpl.java, src/main/java/com/example/spot/service/study/StudyQueryService.java, src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java, src/main/java/com/example/spot/web/controller/MemberController.java, src/main/java/com/example/spot/web/controller/SearchController.java, src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java, src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java, src/main/java/com/example/spot/web/dto/search/SearchResponseDTO.java
> #이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/66
<br/>
1. 관심 분야 입력 및 수정
2. 관심 지역 입력 및 수정
3. 개인 정보 입력 및 수정
4. 테스트 용 회원 생성 API
<br/>
=> [FEAT] 마이페이지 및 체크리스트 API 구현

.github/workflows/deploy.yml
> #이슈 번호, #이슈 링크  https://github.com/SPOTeam/Server/issues/81
=> [fix] deploy workflow 수정

.github/workflows/deploy.yml, .gitignore, Dockerfile, src/main/java/com/example/spot/api/exception/ExceptionAdvice.java, src/main/java/com/example/spot/config/SentryConfig.java, src/main/java/com/example/spot/web/controller/AdminController.java
> #이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/87
<br/>
1. Sentry가 prod 환경에서만 실행 되도록 설정 추가 
2. workflow 및 Dockerfile 수정
=> [FIX] Sentry Prod 환경에서만 실행 되도록 수정

.gitignore, src/main/java/com/example/spot/api/code/status/ErrorStatus.java, src/main/java/com/example/spot/service/post/PostCommandServiceImpl.java, src/main/java/com/example/spot/validation/annotation/ExistPost.java, src/main/java/com/example/spot/validation/validator/ExistPostValidator.java, src/main/java/com/example/spot/web/controller/AdminController.java, src/main/java/com/example/spot/web/controller/AuthController.java, src/main/java/com/example/spot/web/controller/MemberController.java, src/main/java/com/example/spot/web/controller/MemberStudyController.java, src/main/java/com/example/spot/web/controller/NotificationController.java, src/main/java/com/example/spot/web/controller/PostController.java, src/main/java/com/example/spot/web/controller/SearchController.java, src/main/java/com/example/spot/web/controller/StudyController.java, src/main/java/com/example/spot/web/dto/post/PostCreateRequest.java, src/main/java/com/example/spot/web/dto/post/PostCreateResponse.java
> #이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/59
<br/>
1. 스웨거 명세서 기능 별 분류 -> 개발 상태, 기능 별로 분류 되어있음
2. 게시글 관련 API Validation 코드 추가
<br/>
<br/>
=> [REFACTOR] 코드 리팩토링 및 Swagger 명세서 수정 

src/main/java/com/example/spot/api/code/status/ErrorStatus.java, src/main/java/com/example/spot/domain/Member.java, src/main/java/com/example/spot/domain/StudyReason.java, src/main/java/com/example/spot/domain/enums/Reason.java, src/main/java/com/example/spot/repository/StudyReasonRepository.java, src/main/java/com/example/spot/service/member/MemberService.java, src/main/java/com/example/spot/service/member/MemberServiceImpl.java, src/main/java/com/example/spot/web/controller/MemberController.java, src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java, src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
> #이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/91
<br/>
1. 테스트 용 관리자 권한 부여 API 
2. 스터디 이유 설정 및 수정 API
3. 내 관심 지역/테마/스터디 이유 조회 API
=> [FEAT] 관리자 권한 부여 및 회원 관련 기능 구현

src/main/java/com/example/spot/web/dto/post/PostBest5DetailResponse.java, src/main/java/com/example/spot/web/dto/post/PostPagingDetailResponse.java, src/main/java/com/example/spot/web/dto/post/PostRepresentativeDetailResponse.java
> #95 
<br/>
1. 게시글 전체 조회시 게시글 id 반환
2. 게시판 홈 인기글 및 공지 조회시 게시글 id 반환
3. 게시판 홈 게시글 조회시 게시글 id 반환
<br/>
<br/>
> 확인 부탁드립니다!
=> [modify] 게시글 관련 응답 수정

src/main/java/com/example/spot/api/code/status/ErrorStatus.java, src/main/java/com/example/spot/api/code/status/SuccessStatus.java, src/main/java/com/example/spot/domain/Member.java, src/main/java/com/example/spot/domain/MemberReport.java, src/main/java/com/example/spot/domain/enums/ReportStatus.java, src/main/java/com/example/spot/domain/study/StudyPost.java, src/main/java/com/example/spot/domain/study/StudyPostReport.java, src/main/java/com/example/spot/repository/MemberReportRepository.java, src/main/java/com/example/spot/repository/StudyPostReportRepository.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java, src/main/java/com/example/spot/validation/annotation/IntSize.java, src/main/java/com/example/spot/validation/validator/IntSizeValidator.java, src/main/java/com/example/spot/web/controller/MemberStudyController.java, src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java, src/main/java/com/example/spot/web/dto/memberstudy/request/StudyMemberReportDTO.java, src/main/java/com/example/spot/web/dto/memberstudy/request/StudyPostRequestDTO.java, src/main/java/com/example/spot/web/dto/memberstudy/request/StudyVoteRequestDTO.java, src/main/java/com/example/spot/web/dto/study/response/StudyInfoResponseDTO.java
- #74 
<br/>
- [스터디 신고] 스터디 회원 신고
- [스터디 신고] 스터디 게시글 신고
<br/>
<br/>
=> [FEAT] 누락된 API 구현

src/main/java/com/example/spot/repository/querydsl/impl/PostRepositoryImpl.java, src/main/java/com/example/spot/web/controller/PostController.java, src/main/java/com/example/spot/web/dto/post/PostCreateRequest.java, src/main/java/com/example/spot/web/dto/post/PostCreateResponse.java
> #102
<br/>
> 게시글 댓글 관련 Swagger 수정
<br/>
<br/>
=> [refactor] 게시글 댓글 관련 Swagger 수정

src/test/java/com/example/spot/service/study/StudyCommandServiceTest.java, src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
#이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/100
<br/>
1. 스터디 조회 서비스 테스트 코드 작성
<br/>
<br/>
테스트 코드 작성 하실 때, 참고 바랍니다!
=> [FEAT] 스터디 조회 기능 서비스 테스트 코드 작성

src/main/java/com/example/spot/service/studypost/StudyPostCommandService.java, src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java, src/main/java/com/example/spot/web/controller/MemberStudyController.java, src/main/java/com/example/spot/web/controller/StudyController.java, src/main/java/com/example/spot/web/controller/StudyPostController.java
- #109 
<br/>
- StudyController, StudyPostController, StudyPostController 스웨거 명세 수정
<br/>
> 
=> [docs] Swagger 명세 수정

src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java, src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java, src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java, src/main/java/com/example/spot/web/controller/PostController.java, src/main/java/com/example/spot/web/dto/search/SearchResponseDTO.java, src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
> ex) #이슈 번호, #이슈 링크  : https://github.com/SPOTeam/Server/issues/113
<br/>
1. 스터디 조회 시, Response에 MaxPeople 추가 
2. 스터디 조회 시, 가입 된 스터디는 중복 조회 되지 않도록 수정 
3. 게시글 스웨거 명세서 수정
=> [REFACTOR] 스터디 조회 요구 사항 반영 위한 리팩토링

src/main/java/com/example/spot/repository/PreferredStudyRepository.java, src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java, src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
> #이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/116
<br/>
스터디 조회 시, totalPage 값 제대로 적용 안되는 오류 수정
<br/>
=> [FIX] 스터디 조회 시, totalPage 값 제대로 적용 안되는 오류 수정

src/main/java/com/example/spot/api/code/status/ErrorStatus.java, src/main/java/com/example/spot/api/code/status/SuccessStatus.java, src/main/java/com/example/spot/api/exception/ExceptionAdvice.java, src/main/java/com/example/spot/domain/Member.java, src/main/java/com/example/spot/domain/study/Study.java, src/main/java/com/example/spot/domain/study/ToDoList.java, src/main/java/com/example/spot/repository/ToDoListRepository.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java, src/main/java/com/example/spot/validation/annotation/ExistToDoList.java, src/main/java/com/example/spot/validation/validator/ExistToDoListValidator.java, src/main/java/com/example/spot/web/controller/AdminController.java, src/main/java/com/example/spot/web/controller/MemberStudyController.java, src/main/java/com/example/spot/web/dto/memberstudy/request/toDo/ToDoListRequestDTO.java, src/main/java/com/example/spot/web/dto/memberstudy/request/toDo/ToDoListResponseDTO.java
> #이슈 번호, #이슈 링크 : https://github.com/SPOTeam/Server/issues/119
<br/>
1. 스터디 To-Do List CRUD
2. To-Do List 애노테이션 Validator 구현 및 적용
3. ExceptionAdvice 클래스 내 MethodArgumentTypeMismatchException 발생 시, 반환되는 메시지 내용 수정 
<br/>
=> [FEAT] To-do list 기능 구현

src/main/java/com/example/spot/repository/LikedPostCommentRepository.java, src/main/java/com/example/spot/repository/LikedPostRepository.java, src/main/java/com/example/spot/service/post/LikedPostCommentQueryService.java, src/main/java/com/example/spot/service/post/LikedPostCommentQueryServiceImpl.java, src/main/java/com/example/spot/service/post/LikedPostQueryService.java, src/main/java/com/example/spot/service/post/LikedPostQueryServiceImpl.java, src/main/java/com/example/spot/service/post/PostCommandServiceImpl.java, src/main/java/com/example/spot/service/post/PostQueryServiceImpl.java, src/main/java/com/example/spot/web/dto/post/CommentCreateRequest.java, src/main/java/com/example/spot/web/dto/post/CommentDetailResponse.java, src/main/java/com/example/spot/web/dto/post/PostCreateRequest.java, src/main/java/com/example/spot/web/dto/post/PostPagingDetailResponse.java, src/main/java/com/example/spot/web/dto/post/PostSingleResponse.java
> #121
<br/>
1. 익명 처리 오류 수정
2. 현재 사용자 게시글 좋아요 여부
3. 현재 사용자 댓글 좋아요/싫어요 여부
<br/>
> 
<br/>
=> [FEAT] 게시글 좋아요 관련 누락된 기능 구현

src/main/java/com/example/spot/api/code/status/SuccessStatus.java, src/main/java/com/example/spot/service/s3/S3ImageService.java, src/main/java/com/example/spot/web/controller/UtilController.java, src/main/java/com/example/spot/web/dto/util/response/ImageResponse.java
#이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/124
<br/>
1. 이미지 업로드 API 구현
=> [FEAT] 이미지 업로드 API 구현

src/main/java/com/example/spot/web/dto/study/response/StudyInfoResponseDTO.java
#이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/127
<br/>
1. 스터디 정보 조회 시, 최대 인원 수(maxPeople) 정보 반환 하도록 수정
<br/>
=> [REFACTOR] 스터디 정보 조회 시, 최대 인원 수 정보 반환 하도록 수정

src/main/java/com/example/spot/api/code/status/ErrorStatus.java, src/main/java/com/example/spot/domain/Post.java, src/main/java/com/example/spot/domain/mapping/MemberScrap.java, src/main/java/com/example/spot/repository/MemberScrapRepository.java, src/main/java/com/example/spot/service/post/PostCommandService.java, src/main/java/com/example/spot/service/post/PostCommandServiceImpl.java, src/main/java/com/example/spot/service/post/PostQueryService.java, src/main/java/com/example/spot/service/post/PostQueryServiceImpl.java, src/main/java/com/example/spot/web/controller/PostController.java, src/main/java/com/example/spot/web/dto/post/PostPagingDetailResponse.java, src/main/java/com/example/spot/web/dto/post/PostSingleResponse.java, src/main/java/com/example/spot/web/dto/post/ScrapAllDeleteRequest.java, src/main/java/com/example/spot/web/dto/post/ScrapPostResponse.java, src/main/java/com/example/spot/web/dto/post/ScrapsPostDeleteResponse.java
> #104
<br/>
1. 스크랩 API 구현
2. 스크랩 취소 API 구현
3. 마이페이지 스크랩 조회 API 구현
4. 스크랩 모두 삭제 API 구현
<br/>
> 
<br/>
=> [FEAT] 게시글 스크랩 관련 API 구현

src/main/java/com/example/spot/web/dto/search/SearchResponseDTO.java
> #이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/139
<br/>
1. StudyPreview DTO에 스터디 목표 추가
<br/>
<br/>
=> [REFACTOR] 스터디 조회 시 반환 값에 스터디 목표 추가

src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java, src/main/java/com/example/spot/web/controller/NotificationController.java
>  #이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/142
<br/>
1. 스터디 멤버인지 확인하는 로직 제거 
<br/>
=> [REFACTOR] 스터디 멤버가 아니라도 스터디 참여 멤버 조회 가능하도록 기능 수정

src/main/java/com/example/spot/api/code/status/ErrorStatus.java, src/main/java/com/example/spot/repository/MemberStudyRepository.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java, src/main/java/com/example/spot/web/controller/MemberStudyController.java, src/main/java/com/example/spot/web/dto/study/response/StudyInfoResponseDTO.java, src/main/java/com/example/spot/web/dto/study/response/StudyMemberResponseDTO.java
> #이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/145
<br/>
1. 알림을 통해 신청자가 최종 승인 한 경우만 스터디 멤버 카운트에 포함 되도록 수정
=> [REFACTOR] 스터디의 멤버 카운트 증가 로직 수정

src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
> #이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/160
<br/>
1. 스터디 상세 조회 시, 조회 수 오르도록 내부 로직 수정 
<br/>
=> [FIX] 스터디 상세 조회 시, 조회 수 오르도록 수정

src/main/java/com/example/spot/domain/Member.java, src/main/java/com/example/spot/repository/PreferredStudyRepository.java, src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java, src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java, src/main/java/com/example/spot/service/member/MemberService.java, src/main/java/com/example/spot/service/member/MemberServiceImpl.java, src/main/java/com/example/spot/service/study/StudyQueryService.java, src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java, src/main/java/com/example/spot/web/controller/MemberController.java, src/main/java/com/example/spot/web/controller/SearchController.java, src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java, src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
>  #이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/165
<br/>
1. 전체 스터디 조건 별 조회 API 구현
<br/>
=> [FEAT] 전체 스터디 조회 API 구현

src/main/java/com/example/spot/domain/study/StudyPost.java, src/main/java/com/example/spot/repository/StudyLikedPostRepository.java, src/main/java/com/example/spot/repository/StudyPostCommentRepository.java, src/main/java/com/example/spot/repository/StudyPostImageRepository.java, src/main/java/com/example/spot/repository/StudyPostReportRepository.java, src/main/java/com/example/spot/service/s3/S3ImageService.java, src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java, src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java, src/main/java/com/example/spot/web/controller/StudyPostController.java, src/main/java/com/example/spot/web/dto/memberstudy/request/StudyPostRequestDTO.java
- #167 
<br/>
- S3 업로드 오류 해결
- 댓글 개수가 증가하지 않는 문제 해결
<br/>
> 
<br/>
=> [fix] 스터디 게시글 기능 오류 수정

src/main/java/com/example/spot/repository/PreferredStudyRepository.java, src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java, src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
> #이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/170
<br/>
1. countByMemberId 메서드 수정
=> [FIX] 찜 한 스터디 count 로직 수정

src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java, src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostResDTO.java
=> [modify] PostDetailDTO 수정 (프로필 이미지 추가)

src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java, src/main/java/com/example/spot/service/study/StudyQueryService.java, src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java, src/main/java/com/example/spot/web/controller/SearchController.java
> #이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/175
<br/>
이전 브랜치에서 작업 중이던 내용을 가져왔습니다. 
1. 메인 화면 용 관심 Best 스터디 조회 API 구현
=> [FEAT] 누락된 스터디 조회 API 구현

src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java, src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java, src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
- #167 
<br/>
- 경민님께서 말씀하셨던 "사진이 열리지 않고 저장되는 문제"가 스터디 게시글에도 동일하게 발생할 것으로 보여 해당 부분을 수정하였습니다.
<br/>
> 
<br/>
=> [modify] Modify DefaultImage Value

src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java, src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java, src/main/java/com/example/spot/service/study/StudyQueryService.java, src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java, src/main/java/com/example/spot/web/controller/SearchController.java
>  #이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/180
<br/>
1. 검색 조건 제외한 전체 스터디 조회 API 구현 
<br/>
=> [FEAT] 검색 조건 제외한 전체 스터디 조회 API 구현

src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
> #이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/186
<br/>
1. 모집 중 스터디 조회 시, 완료 조건 누락된 오류 수정
=> [FIX] 모집 중 스터디 조회 시, 완료 조건 누락된 오류 수정

src/main/java/com/example/spot/repository/querydsl/impl/PostRepositoryImpl.java, src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
=> [HOTFIX] 스터디 조회 조건 누락된 오류 수정 

src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
=> [HOTFIX] 스터디 조회 누락 조건 추가

src/main/java/com/example/spot/api/code/status/ErrorStatus.java, src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java, src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
https://github.com/SPOTeam/Server/issues/192
<br/>
1. `StudyQueryServiceTest` :  중복 되는 코드를 메서드로 추출 
2.  `StudyQueryServiceTest` : 검색 결과가 없는 경우에 대한 테스트 케이스 추가 
3. `findRecommendStudies` 서비스 메서드에 대한 테스트 코드 추가 
4. `findRecommendStudies` 서비스 메서드에 대한 검증 로직 추가 
<br/>
=> [REFACTOR] 추천 스터디 조회 Service 유닛 테스트 코드 작성

src/main/java/com/example/spot/api/code/status/ErrorStatus.java, src/main/java/com/example/spot/api/code/status/SuccessStatus.java, src/main/java/com/example/spot/config/WebSecurity.java, src/main/java/com/example/spot/service/auth/AuthService.java, src/main/java/com/example/spot/service/auth/AuthServiceImpl.java, src/main/java/com/example/spot/web/controller/AuthController.java, src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
- #205 
<br/>
- 일반 로그인 API 구현
<br/>
> 
<br/>
=> [FEAT] 일반 로그인 기능 구현

src/main/java/com/example/spot/api/code/status/ErrorStatus.java, src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java, src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java, src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java, src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
#210 
<br/>
1. 관심 지역 및 분야 스터디 조회 시, 관심 지역 및 분야에 해당하는 스터디 없는 경우 체크
2. 관심 지역 및 분야 스터디 조회 시, 회원의 유효한 관심 지역 및 분야가 없는 경우 체크
3. 이외 조회 하려는 값이 없는 경우, 체크
4. 메서드 주석 추가
=> [FIX] 스터디 조회 관련 검증 로직 수정 

src/main/java/com/example/spot/service/auth/AuthServiceImpl.java, src/main/java/com/example/spot/service/auth/KaKaoOAuthService.java, src/main/java/com/example/spot/service/member/MemberServiceImpl.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java, src/main/java/com/example/spot/service/notification/NotificationCommandServiceImpl.java, src/main/java/com/example/spot/service/notification/NotificationQueryServiceImpl.java, src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java, src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java, src/main/java/com/example/spot/web/controller/MemberStudyController.java
#212 
<br/>
1. 알림, 인증, 스터디 조회 Service 메서드 주석 추가
2. handler 적용 안된 코드 적용
=> [DOCS] 알림, 인증, 스터디 조회 Service 코드 주석 추가 

src/main/java/com/example/spot/domain/Member.java, src/main/java/com/example/spot/service/auth/AuthServiceImpl.java, src/main/java/com/example/spot/web/controller/AuthController.java, src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
- #218 
- SPOT-56
<br/>
- 주민등록번호를 통해 birth 정보와 gender 정보 DB 저장
<br/>
> 
<br/>
=> [MODIFY] 회원가입 생년월일 성별 정보 추가

src/main/java/com/example/spot/api/code/status/SuccessStatus.java, src/main/java/com/example/spot/config/WebSecurity.java, src/main/java/com/example/spot/domain/Member.java, src/main/java/com/example/spot/repository/MemberRepository.java, src/main/java/com/example/spot/repository/verification/VerificationCodeRepositoryImpl.java, src/main/java/com/example/spot/security/filters/JwtAuthenticationFilter.java, src/main/java/com/example/spot/service/auth/AuthService.java, src/main/java/com/example/spot/service/auth/AuthServiceImpl.java, src/main/java/com/example/spot/web/controller/AuthController.java, src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java, src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
- #219 
- SPOT-58
<br/>
- 아이디 찾기 구현 (인증코드 전송 > 이메일 인증 > 아이디 조회)
- 비밀번호 찾기 구현 (인증코드 전송 > 이메일 인증 > 임시 비밀번호 발급)
<br/>
> 
<br/>
=> [FEAT] 아이디/비밀번호 찾기 구현

src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java, src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
- SPOT-72
- #230 
<br/>
- StudyPostQueryServiceImpl 주석 작성
- StudyPostCommandServiceImpl 주석 작성
<br/>
> 
<br/>
=> [DOCS] 스터디 게시글 관련 Service 코드 주석 추가

src/main/java/com/example/spot/api/ApiResponse.java, src/main/java/com/example/spot/api/exception/ExceptionAdvice.java, src/main/java/com/example/spot/config/QuerydslConfig.java, src/main/java/com/example/spot/config/RegionDataLoader.java, src/main/java/com/example/spot/config/RestTemplateConfig.java, src/main/java/com/example/spot/config/S3Config.java, src/main/java/com/example/spot/config/SentryConfig.java, src/main/java/com/example/spot/config/SwaggerConfig.java, src/main/java/com/example/spot/config/WebSecurity.java, src/main/java/com/example/spot/scheduler/HotKeywordScheduler.java, src/main/java/com/example/spot/security/filters/JwtAuthenticationFilter.java, src/main/java/com/example/spot/security/utils/JwtTokenProvider.java, src/main/java/com/example/spot/security/utils/SecurityUtils.java
#228 
<br/>
1. Util 클래스 주석 추가
2. Config 클래스 주석 추가
3. JWT 클래스 주석 추가
=> [DOCS] Util 메서드 및 설정 파일 주석 작성 

src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
- #231 
- SPOT-74
<br/>
- AuthServiceImpl 주석 추가
<br/>
> 
<br/>
=> [DOCS] 일반 로그인 관련 Service 코드 주석 추가

src/main/java/com/example/spot/service/post/PostQueryService.java, src/main/java/com/example/spot/service/post/PostQueryServiceImpl.java, src/main/java/com/example/spot/web/controller/PostController.java
> #220
<br/>
> 좋아요/스크랩 시 조회수 증가 방지 
<br/>
> 
<br/>
=> [MODIFY] 게시글 조회수 구현 방식 변경

src/main/java/com/example/spot/api/code/status/SuccessStatus.java, src/main/java/com/example/spot/config/WebSecurity.java, src/main/java/com/example/spot/repository/MemberRepository.java, src/main/java/com/example/spot/service/auth/AuthService.java, src/main/java/com/example/spot/service/auth/AuthServiceImpl.java, src/main/java/com/example/spot/web/controller/AuthController.java, src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
- #243 
- SPOT-77
<br/>
- 아이디 사용 가능 여부 확인 기능 구현
- 이메일 사용 가능 여부 확인 기능 구현
<br/>
> 
<br/>
=> [FEAT] 아이디 & 이메일 사용 가능 여부 확인하는 기능 구현

src/main/java/com/example/spot/api/code/status/ErrorStatus.java, src/main/java/com/example/spot/config/WebSecurity.java, src/main/java/com/example/spot/domain/Member.java, src/main/java/com/example/spot/domain/enums/LoginType.java, src/main/java/com/example/spot/repository/MemberRepository.java, src/main/java/com/example/spot/service/auth/AuthService.java, src/main/java/com/example/spot/service/auth/AuthServiceImpl.java, src/main/java/com/example/spot/service/auth/NaverOAuthService.java, src/main/java/com/example/spot/web/controller/AuthController.java, src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java, src/main/java/com/example/spot/web/dto/member/naver/NaverCallback.java, src/main/java/com/example/spot/web/dto/member/naver/NaverMember.java, src/main/java/com/example/spot/web/dto/member/naver/NaverOAuthToken.java
<br/>
- [네이버 로그인] 인증코드 발급
- [네이버 로그인] 네이버 로그인/회원가입
- [공통 회원 관리] 닉네임 생성 및 약관 동의
<br/>
- 자세한 사항은 노션 페이지 참고 바랍니다!
<br/>
- ㅎㅎ 깜빡하고 브랜치 이름에 티켓 번호를 안 넣었네요... 다음부터는 잊지 않고 집어넣겠습니다.
=> [FEAT] 네이버 소셜로그인 구현

src/main/java/com/example/spot/api/code/status/SuccessStatus.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java, src/main/java/com/example/spot/web/controller/MemberStudyController.java
- #248 
- SPOT-88
<br/>
- [스터디 출석체크] 출석 퀴즈 불러오기 구현
<br/>
> 
<br/>
=> [FEAT] 스터디 출석 퀴즈 조회하기 구현

src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
- #252 
- SPOT-93
<br/>
- [스터디 일정] 월별 일정 불러오기에서 Period에 따른 일정 반환 오류 해결
<br/>
> 
<br/>
=> [FIX] 스터디 일정 버그 수정

src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
> #259 
<br/>
소셜 로그인 시 더미 전화번호 생기도록 수정
<br/>
=> [FIX] 소셜 로그인 시, 더미 전화번호 값 생기도록 수정

README.md
#264 
<br/>
1. README 파일에 내용 추가 (서버 아키텍쳐, 패키지 구조, 담당 태스크)
혹시나 수정할 내용 있다거나 마음에 안드는 부분 있으면 리뷰나 슬랙으로 말씀해주세요!
=> [DOCS] SPOT Server Repo README 업데이트 

src/main/java/com/example/spot/api/code/status/ErrorStatus.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
<br/>
- Period 일정 관련 예외 처리
<br/>
> 
<br/>
=> [FIX] Period 일정 시작일 종료일 제한

src/main/java/com/example/spot/web/dto/memberstudy/response/StudyQuizResponseDTO.java
- #273 
- SPOT-124
<br/>
- QuizDTO createdAt 필드 추가
<br/>
> 
<br/>
=> [MODIFY] 퀴즈 조회 시 생성일시 반환하도록 수정

src/main/java/com/example/spot/service/auth/AuthServiceImpl.java, src/main/java/com/example/spot/service/auth/NaverOAuthService.java
- #272 
- SPOT-123
<br/>
- NaverOAuthService 주석 추가
- AuthServiceImpl 주석 추가
<br/>
> 
<br/>
=> [DOCS] 네이버 로그인 관련 서비스 코드 주석 추가

.gitignore, build.gradle
#278 
<br/>
1. 테스트 커버리지 체크를 위해 `Jacoco`를 적용했습니다. 자세한 내용은 `Slack`에 남기겠습니다! 
<br/>
> 
<br/>
=> [CHORE] 테스트 커버리지 체크 툴 Jacoco 적용

src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
#262 
<br/>
핵심 비즈니스 로직인 스터디 및 상세 정보 조회 Service 메서드에 대한 테스트 코드를 작성했습니다!
=> [TEST] 스터디 조회, 상세 정보 Service 메서드 테스트 코드 작성

src/main/java/com/example/spot/service/auth/AuthService.java, src/main/java/com/example/spot/service/auth/AuthServiceImpl.java, src/main/java/com/example/spot/service/auth/NaverOAuthService.java, src/main/java/com/example/spot/web/controller/AuthController.java
<br/>
- 클라이언트에서 피드백 주신대로 SDK를 통해 액세스 토큰 발급 받고 서버 측에서는 네이버 프로필만 호출하도록 변경하였습니다.
<br/>
> 
<br/>
- 클라이언트와 맞춰봐야 해서 빠른 병합이 필요합니다 +++! 🤩
=> [MODIFY] 네이버 로그인 방식 변경

src/main/java/com/example/spot/domain/mapping/MemberStudy.java, src/main/java/com/example/spot/domain/study/Schedule.java, src/main/java/com/example/spot/web/dto/memberstudy/request/ScheduleRequestDTO.java, src/test/java/com/example/spot/service/studyschedule/StudyScheduleCommandServiceTest.java, src/test/java/com/example/spot/service/studyschedule/StudyScheduleQueryServiceTest.java
- #282 
- SPOT-131
<br/>
- 스터디 일정 생성 API 테스트 구현
- 스터디 일정 수정 API 테스트 구현
- 스터디 월별 일정 조회 API 테스트 구현
- 스터디 일정 조회 API 테스트 구현
<br/>
> 
<br/>
- 테스트 코드 작성 경험이 거의 없어서 코드가 중복되거나 지저분한 부분이 많아요...! 피드백 대환영입니당
=> [TEST] 스터디 일정 API 테스트 코드 작성

src/test/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceTest.java
#286 
<br/>
- 스터디 모집 및 신청에 대한 조회 메서드 위주로 테스트 코드 작성을 통한 비즈니스 로직 검증을 진행 했습니다.
=> [TEST] 스터디 모집 및 신청 관련 조회 메서드 테스트 코드 작성

src/main/java/com/example/spot/config/WebSecurity.java, src/main/java/com/example/spot/web/controller/AuthController.java
- #283 
- SPOT-130
<br/>
- WebConfig 수정 (RequestMatchers에 네이버 로그인 URI가 미포함되어 있었습니다... 허허)
- Annotation 수정
<br/>
> 
<br/>
=> [FIX] Fix Annotations and RequestMatchers

src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java, src/main/java/com/example/spot/service/study/StudyCommandService.java, src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java, src/main/java/com/example/spot/web/controller/MemberStudyController.java, src/main/java/com/example/spot/web/controller/StudyController.java
- #298 
- SPOT-140
<br/>
- applyToStudy(스터디 신청) 엔드포인트 수정
- registerStudy(스터디 등록) 엔드포인트 수정
- withdrawFromStudy(스터디 탈퇴) 엔드포인트 수정
<br/>
> 
<br/>
=> [REFACTOR] 담당 API 엔드포인트 수정

.github/workflows/deploy.yml, src/main/java/com/example/spot/config/WebSecurity.java, src/main/java/com/example/spot/web/controller/UtilController.java
#300 
<br/>
배포 할 때 마다 서버가 다운되어 API를 호출할 수 없는 어려움(?)을 무중단 배포를 통해 해결하고자 합니다! 
여러 방식이 있지만, 저희 서버의 리소스와 다른 요소들을 고려 했을 때, Blue-Green 배포가 가장 적합한 방식이라고 생각 했습니다. 다음 회의나 Slack 및 Notion을 통해 더 자세히 정리해 보겠습니다! 
+ 로컬 환경에서는 평소 사용하던 것 처럼 사용하시면 됩니다~!
=> [FEAT] 무중단 배포 도입 : Blue-Green 배포 적용

.github/workflows/deploy.yml
=> [HOTFIX] 스크립트 문법 오류 정정

.github/workflows/deploy.yml
=> [HOTFIX] 서버 상태 확인 전 대기 시간 추가

.github/workflows/deploy.yml
=> [HOTFIX] 서버 재가동 대기 시간 증가

.github/workflows/deploy.yml
=> [HOTFIX] 기존 고아 컨테이너 삭제 후 배포 하도록 수정

.github/workflows/deploy.yml, src/main/java/com/example/spot/web/controller/UtilController.java
#300 
<br/>
1. 새로운 Docker 이미지 가져오도록 수정 
2. 새로운 서버 가동 뒤 대기하는 시간 20s -> 30s
3. Color-check API 수정
=> [FIX] Blue-Green 배포 위한 워크플로우 수정 

src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
- #334 
- SPOT-167
<br/>
- 네이버 회원가입 시 SPOT 기본 프로필 대신 네이버 프로필 이미지가 적용되도록 변경
<br/>
> 
<br/>
=> [MODIFY] 네이버 회원가입 프로필 이미지 변경

src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java, src/main/java/com/example/spot/web/dto/study/response/StudyScheduleResponseDTO.java
- #340 
- SPOT-187
<br/>
- 다가오는 스터디 모임 일정 DTO 수정
<br/>
> 
<br/>
=> [MODIFY] 다가오는 스터디 모임 일정 조회 API 수정

src/main/java/com/example/spot/api/code/status/ErrorStatus.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java, src/test/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceTest.java
- #321 
- SPOT-150
<br/>
- 스터디 탈퇴
- 스터디 탈퇴 (성공)
- 스터디 회원이 아닌 경우 (실패)
- 스터디장인 경우 (실패)
- 스터디 종료
- 스터디 종료 (성공)
- 스터디장이 아닌 경우 (실패)
- 진행중인 스터디가 아닌 경우 (실패)
<br/>
> 
<br/>
=> [TEST] 진행중인 스터디 API 테스트 코드 작성

src/main/java/com/example/spot/api/code/status/ErrorStatus.java, src/main/java/com/example/spot/domain/auth/VerificationCode.java, src/main/java/com/example/spot/repository/verification/VerificationCodeRepositoryImpl.java
- #344 
- SPOT-192
<br/>
- 기존 인증코드 삭제 시 getExpiredAt 필드 null 여부를 필수적으로 검사하도록 변경
- 생성자에 getExpiredAt이 누락되어 있는 오류 수정
<br/>
> 
<br/>
=> [FIX] 인증메일 Null Pointer 오류 해결

src/main/java/com/example/spot/domain/enums/Reason.java, src/main/java/com/example/spot/web/controller/MemberController.java
#355 
<br/>
1. 스터디 참여 이유 관련 수정사항 반영
2. 스터디 참여 이유 조회 시, 응답되는 `SuccessStatus` 변경 
<br/>
=> [REFACTOR] 스터디 참여 이유 관련 수정사항 반영

src/main/java/com/example/spot/api/code/status/SuccessStatus.java, src/main/java/com/example/spot/repository/MemberStudyRepository.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java, src/main/java/com/example/spot/web/controller/MemberStudyController.java, src/main/java/com/example/spot/web/dto/memberstudy/response/StudyMemberResDTO.java
- #362 
- SPOT-235
<br/>
- 스터디 호스트 여부 조회 기능 구현
- isOwned : 로그인한 회원이 호스트인지 true or false로 표시
- host : 스터디 호스트의 id, nickname 표시
<br/>
> 
<br/>
=> [FEAT] 스터디 호스트 여부 조회 기능 구현

src/main/java/com/example/spot/api/code/status/ErrorStatus.java, src/main/java/com/example/spot/repository/MemberStudyRepository.java, src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
- #364 
- SPOT-237
<br/>
- 운영중인 스터디가 존재하는 경우 탈퇴 불가
<br/>
> 
<br/>
=> [FIX] 호스트 회원탈퇴 예외처리 추가

src/main/java/com/example/spot/domain/study/Study.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java, src/main/java/com/example/spot/web/controller/MemberStudyController.java, src/test/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceTest.java
- #365 
- SPOT-238
<br/>
- 스터디 끝내기 시 성과를 입력받을 수 있도록 변경
- Study 도메인 변경 -> performance(성과) 필드 추가
- 히스토리에서 성과를 확인하는 기능은 아직 구현되지 않았습니다
<br/>
> 
<br/>
=> [MODIFY] 스터디 끝내기 성과 로직 추가

src/main/java/com/example/spot/api/code/status/SuccessStatus.java, src/main/java/com/example/spot/service/auth/AuthService.java, src/main/java/com/example/spot/service/auth/AuthServiceImpl.java, src/main/java/com/example/spot/web/controller/AuthController.java, src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
> #401 
<br/>
1. 해당 서비스 가입 여부를 조회하여 응답하는 API 제작  (기준은 체크리스트 작성 유무)
<br/>
> 
<br/>
=> [FEAT] 해당 서비스 가입 유무 조회 API 제작 

src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
- #404 
- SPOT-261
<br/>
- 닉네임 생성 및 약관 동의 API 응답에 nickname 추가
<br/>
> 
<br/>
=> [FEAT] 닉네임 생성 및 약관 동의 API 응답에 `nickname` 추가

src/main/java/com/example/spot/service/member/MemberService.java, src/main/java/com/example/spot/service/member/MemberServiceImpl.java, src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java, src/main/java/com/example/spot/web/controller/MemberController.java
- #422 
<br/>
- 스터디 회원 조회 시, 이름 대신 닉네임 반환
- 회원 닉네임 조회 API 생성
<br/>
> 
<br/>
=> [REFACTOR] 스터디 회원 조회 시, 이름 대신 닉네임 반환

.github/workflows/deploy.yml
- #434 
<br/>
- 도메인 변경으로 인한 배포 워크플로우 수정
<br/>
> 
<br/>
=> [REFACTOR] 도메인 변경으로 인한 배포 워크플로우 수정

.github/workflows/deploy.yml
- #434 
<br/>
- 워크플로우 내 이전 도메인 명 삭제
<br/>
> 
<br/>
=> [REFACTOR] 누락된 변경 사항 반영

src/main/java/com/example/spot/repository/querydsl/impl/PostRepositoryImpl.java
- #442 
<br/>
- 현재는 최근 2시간 이내의 글만 집계 중
- 전체 글을 대상으로 집계 하도록 로직 수정
<br/>
> 
<br/>
=> [FEATURE] 실시간 인기글 필터링 로직 변경

src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
- #445 
<br/>
-  회원 탈퇴 시 발생하는 IntegrityConstraintViolationException을 일시적 물리 삭제로 해결
<br/>
> 
<br/>
=> [FIX] 회원 탈퇴 시 발생하는 IntegrityConstraintViolationException 해결
