- src/main/java/com/example/spot/api/code/status/ErrorStatus.java
- src/main/java/com/example/spot/config/SwaggerConfig.java
- src/main/java/com/example/spot/config/WebSecurity.java
- src/main/java/com/example/spot/domain/Member.java
- src/main/java/com/example/spot/domain/auth/CustomUserDetails.java
- src/main/java/com/example/spot/domain/auth/RefreshToken.java
- src/main/java/com/example/spot/repository/RefreshTokenRepository.java
- src/main/java/com/example/spot/security/filters/JwtAuthenticationFilter.java
- src/main/java/com/example/spot/security/utils/JwtTokenProvider.java
- src/main/java/com/example/spot/security/utils/SecurityUtils.java
- src/main/java/com/example/spot/service/auth/AuthService.java
- src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
- src/main/java/com/example/spot/service/auth/KaKaoOAuthService.java
- src/main/java/com/example/spot/service/member/MemberServiceImpl.java
- src/main/java/com/example/spot/service/oauth/AuthService.java
- src/main/java/com/example/spot/service/oauth/KaKaoOAuthService.java
- src/main/java/com/example/spot/validation/validator/MemberValidator.java
- src/main/java/com/example/spot/web/AuthController.java
- src/main/java/com/example/spot/web/controller/AuthController.java
- src/main/java/com/example/spot/web/controller/MemberController.java
- src/main/java/com/example/spot/web/controller/SearchController.java
- src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
- src/main/java/com/example/spot/web/dto/member/kakao/KaKaoUser.java
- src/main/java/com/example/spot/web/dto/token/TokenResponseDTO.java
> #이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/69
<br/>
1. JWT 기반 Refresh Token 발급
2. Refresh Token을 통한 Access Token 재발급
3.  Access Token에 담긴 회원 정보와 현재 API를 요청하는 회원 정보의 일치 여부 판단 하는 메서드 구현(권한 판단)
1. 카카오 소셜 로그인 엔드 포인트가 `/spot/login/kakao` 로 변경 되었습니다.
2. 로그인 및 테스트 회원 생성 시, 이제`refreshToken`도 발급 됩니다. `refreshToken`은 `accessToken`의 만료 시 재발급에 사용되는 토큰으로, 다른 API 사용 시에는 사용하실 필요는 없습니다. 
3.  `accessToken`이 만료 되었다면,  `refreshToken`을 통해 재발급 받아야 합니다. 재발급 시, `accessToken`만 재발급 되는 것이 아닌,  `refreshToken` 또한 재발급 되므로 기존에 사용하던  `refreshToken`은 더 이상 사용하실 수 없습니다. 
4. `spot/security/utils/SecurityUtils.java` 파일 내 권한을 판단 하는 메서드가 작성되었습니다.`accessToken`에 담긴 회원 정보와 현재 API를 요청하는 회원 정보의 일치 여부를 판단하기 원하시면, 해당 메서드를 사용하시면 됩니다. 
<br/>
회원 가입 시
---
---
---
<br/>
> [FEAT] JWT 기반 Refresh Token 통한 세션 유지 기능 

- src/main/java/com/example/spot/api/code/status/ErrorStatus.java
- src/main/java/com/example/spot/domain/LikedPostComment.java
- src/main/java/com/example/spot/domain/PostComment.java
- src/main/java/com/example/spot/repository/LikedPostCommentRepository.java
- src/main/java/com/example/spot/repository/PostCommentRepository.java
- src/main/java/com/example/spot/repository/querydsl/impl/PostRepositoryImpl.java
- src/main/java/com/example/spot/service/post/LikedPostCommentQueryService.java
- src/main/java/com/example/spot/service/post/LikedPostCommentQueryServiceImpl.java
- src/main/java/com/example/spot/service/post/PostCommandService.java
- src/main/java/com/example/spot/service/post/PostCommandServiceImpl.java
- src/main/java/com/example/spot/service/post/PostQueryService.java
- src/main/java/com/example/spot/service/post/PostQueryServiceImpl.java
- src/main/java/com/example/spot/web/controller/PostController.java
- src/main/java/com/example/spot/web/dto/post/CommentCreateRequest.java
- src/main/java/com/example/spot/web/dto/post/CommentCreateResponse.java
- src/main/java/com/example/spot/web/dto/post/CommentDetailResponse.java
- src/main/java/com/example/spot/web/dto/post/CommentLikeResponse.java
- src/main/java/com/example/spot/web/dto/post/CommentResponse.java
- src/main/java/com/example/spot/web/dto/post/PostPagingDetailResponse.java
- src/main/java/com/example/spot/web/dto/post/PostSingleResponse.java
> #86 
<br/>
1. 댓글 등록 API 구현
2. 전체 댓글 조회 API 구현
3. 댓글 좋아요 생성/삭제 API 구현
4. 댓글 싫어요 생성/삭제 API 구현
<br/>
> 
<br/>
> 댓글 조회 게시글 단건 조회시 함께 조회되도록 하였고 테스트용으로 댓글 조회 API 추가해 두긴 했습니다~ 코드 확인 부탁드립니다!!
> 게시판 댓글 관련 API 구현

- src/main/java/com/example/spot/api/code/status/ErrorStatus.java
- src/main/java/com/example/spot/security/utils/SecurityUtils.java
- src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
- src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
- src/main/java/com/example/spot/web/controller/MemberController.java
- src/main/java/com/example/spot/web/controller/MemberStudyController.java
- src/main/java/com/example/spot/web/controller/SearchController.java
- src/main/java/com/example/spot/web/controller/StudyController.java
- src/main/java/com/example/spot/web/dto/study/request/StudyRegisterRequestDTO.java
> #이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/94
<br/>
1. 회원 관련 API 적용
2. 스터디 조회 API 적용
3. 스터디 관련 기능 API 적용
<br/>
> [FEAT] 담당 API에 SecurityUtils 통한 사용자 인증/인가 로직 추가

- src/main/java/com/example/spot/repository/StudyLikedPostRepository.java
- src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
- src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostCommentResponseDTO.java
- src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostResDTO.java
- #132 
<br/>
- 게시글과 댓글을 조회할 때 로그인한 회원의 좋아요/싫어요 여부를 확인할 수 있도록 수정하였습니다.
<br/>
> 
<br/>
> [modify] 내 스터디 게시글 조회 기능 수정

- src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
- src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
- src/main/java/com/example/spot/web/dto/search/SearchResponseDTO.java
- src/main/java/com/example/spot/web/dto/study/response/StudyInfoResponseDTO.java
- src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
> #이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/148
<br/>
1. memberCount 및 isLike 조회 시 반영 안되는 오류 수정
<br/>
> [FIX] memberCount 및 isLike 조회 시 반영 안되는 오류 수정

- src/main/java/com/example/spot/web/dto/search/SearchResponseDTO.java
>#이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/151
<br/>
1. status가 LIKED인 경우만 필터링 하도록 수정
> [FIX] isLike 조회 시, status가 LIKED인 경우만 필터링 하도록 수정

- src/main/java/com/example/spot/repository/PreferredStudyRepository.java
- src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
- src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
> #이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/154
<br/>
1. StudyQueryService 찜 한 스터디 조회 로직 수정
> [FIX] 찜한 스터디 조회 시, 비활성화 된 찜 스터디도 조회 되는 오류 수정

- src/main/java/com/example/spot/domain/enums/ApplicationStatus.java
- src/main/java/com/example/spot/repository/MemberStudyRepository.java
- src/main/java/com/example/spot/repository/NotificationRepository.java
- src/main/java/com/example/spot/repository/RefreshTokenRepository.java
- src/main/java/com/example/spot/service/member/MemberServiceImpl.java
- src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
- src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
- src/main/java/com/example/spot/service/notification/NotificationCommandServiceImpl.java
- src/main/java/com/example/spot/service/notification/NotificationQueryServiceImpl.java
- src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
- src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
- src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
- src/main/java/com/example/spot/web/dto/study/response/StudyInfoResponseDTO.java
> #이슈 번호, #이슈 링크 https://github.com/SPOTeam/Server/issues/157
<br/>
1. 처리된 스터디 알림은 조회 되지 않도록 로직 수정
2. 리프레쉬 토큰이 로그인 마다 DB에 중복 저장 되던 문제 해결
3. 스터디 조회 시, OWNER 정보 얻을 수 있도록 수정
4. 거절 및 취소 한 스터디 다시 신청 가능하도록 수정 
5. 4번으로 인해 memberStudy가 중복 조회 되던 오류 수정
> [REFACTOR] 스터디 관련 요구사항 반영

- src/main/java/com/example/spot/domain/study/StudyPost.java
- src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
- src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostResDTO.java
- #167 
<br/>
- 스터디 게시글 댓글 수 조회 방식 변경 (+1 방식이 아닌 DB에서 댓글 수를 불러오는 방식)
- 스터디 게시글 조회 DTO에 작성자 이름 추가
<br/>
> 
<br/>
> [MODIFY] 스터디 게시글 댓글 수 조회 방식 변경 & DTO에 이름 추가

- src/main/java/com/example/spot/service/post/PostQueryServiceImpl.java
- src/main/java/com/example/spot/service/s3/S3ImageService.java
- src/main/java/com/example/spot/web/dto/post/CommentDetailResponse.java
- src/main/java/com/example/spot/web/dto/post/PostSingleResponse.java
>  #163
<br/>
1. 게시글 및 댓글 조회 시 작성자 프로필 이미지 반환하도록 수정
2. 익명 작성자 여부 확인 후  익명 프로필 사진 반환
3. 익명 작성자 여부 반환
<br/>
> 
<br/>
> [REFACTOR] 게시글 및 댓글 조회 시 작성자 프로필 이미지 반환하도록 수정

- src/main/java/com/example/spot/repository/querydsl/impl/PostRepositoryImpl.java
> #183
<br/>
> 댓글순 인기글 반환 안되는 오류 해결
<br/>
> 
<br/>
> [fix] 댓글순 인기글 반환 안되는 오류 해결

- src/main/java/com/example/spot/service/member/MemberServiceImpl.java
- src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
- src/main/java/com/example/spot/web/dto/member/kakao/KaKaoUser.java
#222 
<br/>
1. 소셜 로그인 및 테스트 회원 생성 시, 닉네임도 처리 하도록 수정
> [HOTFIX] 소셜 로그인 및 테스트 회원 생성 시, 닉네임도 처리 하도록 수정

- build.gradle
- src/main/java/com/example/SpotApplication.java
- src/main/java/com/example/spot/api/code/status/ErrorStatus.java
- src/main/java/com/example/spot/api/code/status/SuccessStatus.java
- src/main/java/com/example/spot/config/RedisConfig.java
- src/main/java/com/example/spot/scheduler/HotKeywordScheduler.java
- src/main/java/com/example/spot/service/study/StudyCommandService.java
- src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
- src/main/java/com/example/spot/service/study/StudyQueryService.java
- src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
- src/main/java/com/example/spot/web/controller/SearchController.java
- src/main/java/com/example/spot/web/dto/search/SearchResponseDTO.java
#217 
<br/>
1. Redis 도입 
2. 스터디 검색 시, Redis 상의 검색 키워드에 해당하는 Count 값이 증가 함
3. 매일 13시, 18시에 Count 값 기준으로 인기 검색어 갱신 (스케줄러 사용) 
--- 
아래 링크 통해서 Redis 설치한 뒤, application.yml 파일에 해당 기능과 관련된 값 추가 해야 정상적으로 코드가 실행 됩니다.  Slack에 추가할 내용 공유 하겠습니다. 
https://wlswoo.tistory.com/44
<br/>
> [FEAT] 인기 검색어 조회 기능 구현 

- src/main/java/com/example/spot/security/utils/MemberUtils.java
- src/main/java/com/example/spot/web/dto/member/kakao/KaKaoUser.java
> #235 
<br/>
1. 전화번호 랜덤 생성 유틸 메서드를 통해 카카오 로그인 시 전화 번호 중복 방지
> [FIX] 전화번호 랜덤 생성되게 하여 중복 방지

- src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
- src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
- src/main/java/com/example/spot/web/controller/MemberStudyController.java
<br/>
- 진행중인 스터디 탈퇴/종료 기능 주석 추가
- 스터디 일정 기능 주석 추가
- 스터디 투표 기능 주석 추가
- 스터디 출석체크 기능 주석 추가
- 스터디 갤러리 기능 주석 추가
주석 달면서 예외처리 제대로 안 된 부분 발견... -> 다음 스프린트 때 수정
<br/>
> 
<br/>
> [DOCS] 스터디 내부 기능 Service 코드 주석 추가

- src/main/java/com/example/spot/api/code/status/ErrorStatus.java
- src/main/java/com/example/spot/domain/Quiz.java
- src/main/java/com/example/spot/domain/study/Schedule.java
- src/main/java/com/example/spot/domain/study/Study.java
- src/main/java/com/example/spot/repository/QuizRepository.java
- src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandService.java
- src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
- src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryService.java
- src/main/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceImpl.java
- src/main/java/com/example/spot/web/controller/MemberStudyController.java
- src/main/java/com/example/spot/web/dto/memberstudy/request/StudyQuizRequestDTO.java
- src/main/java/com/example/spot/web/dto/memberstudy/response/StudyQuizResponseDTO.java
- #255 
- SPOT-101
<br/>
- Quiz 도메인 수정 : createdAt을 프론트에서 받고, studyId 대신 scheduleId를 외래키로 받도록 수정했습니다
- 출석퀴즈 관련 API 전체 수정 : 현재 출석퀴즈가 일정과 연동이 되어있지 않아(스터디랑만 연동이 되어있어) 요구사항대로 API가 동작하지 않았던 것으로 확인됩니다...! 따라서 모든 출석퀴즈 API를 일정과 연동하는 방향으로 수정하였습니다.
<br/>
> 
<br/>
> [MODIFY] 출석 퀴즈에 일정 연결

- src/main/java/com/example/spot/api/code/status/ErrorStatus.java
- src/main/java/com/example/spot/domain/Member.java
- src/main/java/com/example/spot/repository/MemberRepository.java
- src/main/java/com/example/spot/security/oauth/CustomOAuth2UserService.java
- src/main/java/com/example/spot/security/oauth/CustomOAuthSuccessHandler.java
- src/main/java/com/example/spot/service/auth/AuthService.java
- src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
- src/main/java/com/example/spot/service/member/MemberService.java
- src/main/java/com/example/spot/service/member/MemberServiceImpl.java
- src/main/java/com/example/spot/web/controller/AuthController.java
- src/main/java/com/example/spot/web/controller/MemberController.java
- src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
- src/main/java/com/example/spot/web/dto/member/google/CustomOAuth2User.java
#263 
<br/>
- 동일한 이메일로 다른 종류의 소셜 로그인을 사용할 시, 이메일 중복으로 인한 데이터 무결성 에러가 발생
- 이를 해결하기 위해 소셜 로그인 시, 해당 이메일의 가입 유무를 확인하여 적절히 응답
- 또한, Naver 소셜 로그인과 다른 소셜 로그인의 응답을 통일 -> `isSpotMember` 추가 
- 로그인 및 회원 가입 시, `LoginType` 도 함께 응답 하도록 추가
<br/>
> 
1. 카카오로 가입된 이메일을 네이버로 로그인 하려고 시도 했을 때 응답한 메시지 -> 이메일 중복
2. 구글 -> 회원 가입 성공 예시 
3. 구글 -> 회원 가입 후 다시 로그인 한 경우 -> (2, 3번 `isSpotMember` 변경됨)
4. 기본 로그인 예시
<br/>
> [FIX] 소셜 로그인 시, 중복 가입 되지 않도록 로직 수정 

- src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
#285 
<br/>
스터디 조회 서비스 메서드 대부분의 경우,`조회 된 스터디가 없는 경우`에 대해서 테스트 코드 작성이 미흡했습니다.  
-> 누락된 조건 브랜치에 대해 테스트 코드를 작성하여 비즈니스 로직을 검증 했습니다. 
<br/>
> [TEST] 스터디 조회 메서드 테스트 보강: 조건 브랜치 커버

- src/main/java/com/example/spot/web/controller/MemberController.java
- src/main/java/com/example/spot/web/controller/SearchController.java
- src/main/java/com/example/spot/web/controller/StudyController.java
#294 
<br/>
회원, 스터디 조회, 찜하기 기능 API의 엔드포인트를 수정했습니다. 
- 불필요한 정보인 `MemberId(현재 토큰을 통해 회원을 구분하고 있음)`는 보안 및 가독성 향상을 위해 삭제 
- `member` -> `members`와 같이 복수형으로 변경
관련 변경 내용은 노션에 정리하여 업로드 했습니다!
> [REFACTOR] 담당 API 엔드포인트 수정

- src/main/java/com/example/spot/config/WebSecurity.java
- src/main/java/com/example/spot/service/auth/AuthService.java
- src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
- src/main/java/com/example/spot/service/auth/NaverOAuthService.java
- src/main/java/com/example/spot/web/controller/AuthController.java
<br/>
네이버 로그인 시 내부적으로 네이버 API를 호출하고 JsonProcessingException으로 throw하는 로직이 있었는데, ExceptionAdvice에 JsonProcessingException에 대한 예외 처리를 별도로 구현하지 않아서 Exception으로 throw 하도록 수정했습니다. 
JsonProcessingException이 발생하더라도 저희가 지정한 Json 포맷으로 응답을 전송할 수 있도록 만든 것입니당 😆
<br/>
> 
<br/>
> [FIX] 네이버 로그인에 대한 ExceptionAdvice 적용

- .github/workflows/deploy.yml
- src/main/java/com/example/spot/web/controller/SearchController.java
#316 
<br/>
1. Blue-Green 배포 시, 새로운 서버 가동 후 정상 작동을 확인 해야하는데 다양한 원인(인스턴스 성능 한계 + 스왑 메모리 사용까지...) 으로 인해 서버 가동 될 때 까지 예상보다 많은 시간이 소요 되어서 자꾸 Workflow가 실패하는 문제 발생! -> 그냥 넉넉하게 서버 재가동 대기 시간을 45s -> 75s 까지 증가.  (어제까지는 잘 됐으면서...)
2. 배포 시간이 늘어나는것에 대한 우려가 있을 수도 있습니다!  -> 새로운 서버가 정상적으로 작동하는 것을 확인한 후 기존 서버를 종료하기 때문에, Nginx 리로드 시간 외에는 실제 사용자에게 영향을 미치는 다운타임은 발생하지 않습니다. 따라서 배포 시간의 증가 자체는 큰 문제가 없다고 판단했습니다. 
3. Swagger 상 MemberId가 아직 남아있어서 API 호출에 문제가 발생하는 경우를 발견했고, 이를 수정 했습니다. 
<br/>
> 
<br/>
> [FIX] 배포 Workflow 및 Swagger 명세서 수정

- src/main/java/com/example/spot/api/code/status/ErrorStatus.java
- src/main/java/com/example/spot/service/auth/AuthService.java
- src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
- src/main/java/com/example/spot/web/controller/AuthController.java
- src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
- #322 
- SPOT-152
<br/>
- 일반 회원가입 > 닉네임 생성 및 약관 동의 ResponseDTO 수정
- 일반 회원가입 > 중복 아이디에 대한 예외처리 추가
<br/>
> 
<br/>
> [FIX] 일반 회원가입 로직 수정

- src/test/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceTest.java
- src/test/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceTest.java
- src/test/java/com/example/spot/service/notification/NotificationCommandServiceTest.java
- src/test/java/com/example/spot/service/notification/NotificationQueryServiceTest.java
> #319 
<br/>
1. 알림, TODO 관련 서비스 테스트 코드 작성을 통해 비즈니스 로직 검증
> [TEST] 알림, TODO 관련 서비스 테스트 코드 작성

- .gitignore
- src/main/java/com/example/spot/api/code/status/ErrorStatus.java
- src/main/java/com/example/spot/api/code/status/SuccessStatus.java
- src/main/java/com/example/spot/config/WebSecurity.java
- src/main/java/com/example/spot/domain/auth/RsaKey.java
- src/main/java/com/example/spot/repository/rsa/RSAKeyRepository.java
- src/main/java/com/example/spot/security/utils/RSAUtils.java
- src/main/java/com/example/spot/service/auth/AuthService.java
- src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
- src/main/java/com/example/spot/web/controller/AuthController.java
- src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
- src/main/java/com/example/spot/web/dto/rsa/Rsa.java
- #327 
- SPOT-157
<br/>
- RSA Public Key 발급 API 구현
- 일반 로그인 API 비밀번호 RSA 암호화 적용
- 일반 회원가입 API 비밀번호 RSA 암호화 적용
<br/>
- RSA Public Key를 발급 받아 비밀번호를 암호화한 후 RSA 식별자와 함께 로그인 요청과 회원가입 요청을 보낼 수 있습니다.
- 상세 로직은 노션에 작성하여 슬랙으로 공유할 예정입니다 !!
<br/>
> [FEAT] 로그인 API RSA 암호화 적용

- src/main/java/com/example/spot/service/post/PostQueryServiceImpl.java
- src/main/java/com/example/spot/web/dto/post/PostSingleResponse.java
> #331
<br/>
> 게시글 단건 조회 시 응답에 현재 사용자가 작성자인지 확인하는 필드 추가
<br/>
> 
<br/>
> [MODIFY] 게시글 단건 조회 시 작성자 확인 필드 추가

- src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
- src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
- src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
- src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
> #337 
<br/>
1. 추천 스터디 조회 내부 로직이 변경 되었습니다. 자세한 내용은 화면 설계서 참고 부탁드립니다~
<br/>
> 
<br/>
> [REFACTOR] 추천 스터디 조회 내부 로직 변경

- src/main/java/com/example/spot/api/code/status/ErrorStatus.java
- src/main/java/com/example/spot/domain/mapping/StudyLikedComment.java
- src/main/java/com/example/spot/domain/mapping/StudyLikedPost.java
- src/main/java/com/example/spot/domain/study/Study.java
- src/main/java/com/example/spot/domain/study/StudyPost.java
- src/main/java/com/example/spot/domain/study/StudyPostComment.java
- src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
- src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
- src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
- src/main/java/com/example/spot/web/dto/memberstudy/request/StudyPostCommentRequestDTO.java
- src/main/java/com/example/spot/web/dto/memberstudy/request/StudyPostRequestDTO.java
- src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostCommentResponseDTO.java
- src/test/java/com/example/spot/service/memberstudy/MemberStudyQueryServiceTest.java
- src/test/java/com/example/spot/service/study/StudyCommandServiceTest.java
- src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
- src/test/java/com/example/spot/service/studypost/StudyPostCommandServiceTest.java
- src/test/java/com/example/spot/service/studypost/StudyPostQueryServiceTest.java
- #291 
- SPOT-138
<br/>
- 스터디 게시글 목록 조회
- 전체 게시글 조회 (성공)
- 테마별 게시글 조회 (성공)
- 스터디 회원이 아닌 경우 (실패)
- 존재하는 카테고리가 아닌 경우 (실패)
- 스터디 게시글 단건 조회
- 게시글 단건 조회 (성공)
- 스터디 회원이 아닌 경우 (실패)
- 스터디 게시글이 아닌 경우 (실패)
- 댓글 목록 조회
- 댓글 목록 조회 (성공)
- 스터디 회원이 아닌 경우 (실패)
- 스터디 게시글이 아닌 경우 (실패)
- 스터디 게시글 작성
- 공지 게시글 작성 (성공)
- 일반 게시글 작성 (성공)
- 스터디 회원이 아닌 경우 (실패)
- 스터디장이 아닌 회원이 공지 게시글을 작성하는 경우 (실패)
- 제목이 50자를 초과하는 경우 (실패)
- 스터디 게시글 삭제
- 게시글 삭제 (성공)
- 이미 삭제된 게시글인 경우 (실패)
- 작성자 본인이나 스터디장이 아닌 경우 (실패)
- 스터디 게시글 좋아요
- 게시글 좋아요 (성공)
- 스터디 회원이 아닌 경우 (실패)
- 이미 좋아요를 누른 경우 (실패)
- 스터디 게시글 좋아요 취소
- 게시글 좋아요 취소 (성공)
- 스터디 회원이 아닌 경우 (실패)
- 좋아요를 누르지 않은 게시글인 경우 (실패)
- 스터디 게시글 댓글 작성
- 익명 댓글 (성공)
- 실명 댓글 (성공)
- 스터디 회원이 아닌 경우 (실패)
- 스터디 게시글 답글 작성
- 익명 댓글 (성공)
- 실명 댓글 (성공)
- 스터디 회원이 아닌 경우 …
> [TEST] 스터디 게시글 API 테스트 코드 작성

- src/main/java/com/example/spot/api/code/status/ErrorStatus.java
- src/main/java/com/example/spot/domain/study/StudyPost.java
- src/main/java/com/example/spot/repository/StudyPostImageRepository.java
- src/main/java/com/example/spot/service/studypost/StudyPostCommandService.java
- src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
- src/main/java/com/example/spot/web/controller/StudyPostController.java
- #348 
- SPOT-215
<br/>
- 스터디 게시글 편집 API 구현 (게시글 생성 API와 RequestDTO 통일)
<br/>
> 
<br/>
> [FEAT] 스터디 게시글 편집 API 구현

- src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
- src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostResDTO.java
- #349 
- SPOT-216
<br/>
- PostDetailDTO 수정 -> isWriter 필드 추가
- getPost 요청 시 게시글 작성 여부 반환
<br/>
> 
<br/>
> [MODIFY] 스터디 게시글 조회 시 작성 여부 반환

- src/main/java/com/example/spot/api/code/status/ErrorStatus.java
- src/main/java/com/example/spot/domain/Region.java
- src/main/java/com/example/spot/domain/study/Study.java
- src/main/java/com/example/spot/repository/MemberStudyRepository.java
- src/main/java/com/example/spot/repository/RegionStudyRepository.java
- src/main/java/com/example/spot/repository/StudyThemeRepository.java
- src/main/java/com/example/spot/service/study/StudyCommandService.java
- src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
- src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
- src/main/java/com/example/spot/web/controller/MemberStudyController.java
- src/main/java/com/example/spot/web/controller/StudyController.java
- src/main/java/com/example/spot/web/dto/study/response/StudyInfoResponseDTO.java
#371 
<br/>
1. 스터디 정보 수정 API 구현 
2. 참여 및 모집 중인 스터디 조회 시, 종료 상태 스터디는 조회 하지 않도록 필터링 조건 추가
3. 스터디 세부 정보 조회 시, 지역 정보도 응답. 
<br/>
> 
<br/>
> [FEAT] 스터디 정보 수정 및 관련 API 구현 

- src/main/java/com/example/spot/repository/PostRepository.java
- src/main/java/com/example/spot/service/post/PostQueryServiceImpl.java
- src/test/java/com/example/spot/service/post/PostQueryServiceTest.java
#387 
<br/>
1. 게시글 조회 시, 최신 게시글이 먼저 & 오래된 게시글이 뒤로 오도록 게시글 정렬 순서 변경
<br/>
> 
<br/>
> [MODIFY] 게시글 조회 시 게시글 정렬 순서 변경 

- src/main/java/com/example/spot/service/studypost/StudyPostQueryService.java
- src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
- src/main/java/com/example/spot/web/controller/StudyPostController.java
- src/test/java/com/example/spot/service/studypost/StudyPostQueryServiceTest.java
- #389 
- SPOT-254
<br/>
- 좋아요나 스크랩 직후 게시글 조회 시 조회수가 업데이트 되지 않도록 likeOrScrap 여부에 관한 RequestParam 추가
- likeOrScrap 파라미터에 따른 테스트 로직 추가
<br/>
> 
<br/>
> [MODIFY] 스터디 게시글 조회 시 좋아요/스크랩 확인 로직 추가

- src/main/java/com/example/spot/domain/Post.java
- src/main/java/com/example/spot/service/post/PostCommandServiceImpl.java
- src/main/java/com/example/spot/web/controller/PostController.java
- src/main/java/com/example/spot/web/dto/post/PostUpdateRequest.java
#392 
<br/>
- 게시글 이미지 수정 로직 변경
- 기존 이미지 재사용 원하는 경우, 기존 이미지 URL 업로드
- 이미지 수정 원하는 경우에는 Multipart로 이미지 업로드
<br/>
> 
<br/>
> [MODIFY] 게시글 이미지 수정 로직 변경

- src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
- src/main/java/com/example/spot/service/member/MemberServiceImpl.java
#394 
<br/>
- 소셜 로그인 시, 반환되는 `isSpotMember`의 판단 기준을 변경합니다.
- 기존 회원가입 유무로 판단하여 응답 했지만, 앞으로는 체크리스트 입력 유무를 통해 판단하여 응답합니다.
- 네이버 로그인은 시루님이 한 번 확인 해주시면 감사하겠습니다..! 
<br/>
> 
<br/>
> [MODIFY] 소셜 로그인 시, 반환되는 `isSpotMember` 판단 기준 변경

- src/main/java/com/example/spot/domain/mapping/StudyPostImage.java
- src/main/java/com/example/spot/domain/study/StudyPost.java
- src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
- src/main/java/com/example/spot/web/controller/StudyPostController.java
- src/main/java/com/example/spot/web/dto/memberstudy/request/StudyPostRequestDTO.java
- src/test/java/com/example/spot/service/studypost/StudyPostCommandServiceTest.java
- #399 
- SPOT-259
<br/>
- 게시글 작성 API, 게시글 수정 API Request DTO 변경
(두 API가 같은 DTO를 사용하고 있어서 두 가지 모두 바뀌었습니다!)
- 게시글 작성 API 오류 해결
- 게시글 수정 시 기존 이미지와 신규 이미지 로직을 분리하여 처리하도록 변경
<br/>
> 
<br/>
> [MODIFY] 스터디 게시글 이미지 수정 로직 변경

- src/main/java/com/example/spot/repository/StudyPostRepository.java
- src/main/java/com/example/spot/repository/querydsl/StudyPostRepositoryCustom.java
- src/main/java/com/example/spot/repository/querydsl/impl/StudyPostRepositoryCustomImpl.java
- src/main/java/com/example/spot/service/studypost/StudyPostQueryServiceImpl.java
- src/main/java/com/example/spot/web/dto/memberstudy/response/StudyPostResDTO.java
- src/test/java/com/example/spot/service/studypost/StudyPostQueryServiceTest.java
- #406 
- SPOT-262
<br/>
- 스터디 게시글 페이징 조회 시 전체 페이지 수 반환
- totalPages = 3인 경우 -> offset 요청 파라미터 값으로 0, 1, 2 유효 (3부터는 빈 리스트 반환)
<br/>
> 
<br/>
- 제가 지난주 대면 회의에 못 가서 요청하신 부분이 정확히 요게 맞는지 잘 모르겠네요...!! 확인 부탁드립니당
> [MODIFY] 스터디 게시글 목록 조회 시 전체 페이지 수 반환

- src/main/java/com/example/spot/api/code/status/SuccessStatus.java
- src/main/java/com/example/spot/repository/MemberRepository.java
- src/main/java/com/example/spot/service/auth/AuthService.java
- src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
- src/main/java/com/example/spot/web/controller/AuthController.java
- src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
- src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
#409 
<br/>
1. 닉네임 중복 확인 API 구현 
2. 닉네임 생성 및 약관 동의 API 호출 시, Request Body로 요청 값 받도록 변경 (안드로이드 요청)
<br/>
> 
<br/>
> [FEAT] 닉네임 중복 확인 API 구현

- src/main/java/com/example/spot/domain/Notification.java
- src/main/java/com/example/spot/service/notification/NotificationQueryServiceImpl.java
- src/main/java/com/example/spot/service/studypost/StudyPostCommandServiceImpl.java
- src/main/java/com/example/spot/web/dto/notification/NotificationResponseDTO.java
> #413 
<br/>
1. Notification 엔티티에서 스터디 공지 글 ID를 저장할 수 있게, `studyPostId` 필드 추가 -`StudyPost → Notification`로의 탐색은 필요 없다고 생각해서 정수형 필드만 하나 뒀습니다! 
2. 응답 시 해당 알림이 발생한 스터디의 고유 식별자도 함께 응답하도록 구현
<br/>
> 
<br/>
> [FEAT] 알림 조회 시, 알림이 발생한 지점으로 이동할 수 있도록 응답 값 추가

- src/main/java/com/example/spot/api/code/status/ErrorStatus.java
- src/main/java/com/example/spot/api/code/status/SuccessStatus.java
- src/main/java/com/example/spot/api/exception/ExceptionAdvice.java
- src/main/java/com/example/spot/repository/MemberRepository.java
- src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
- src/main/java/com/example/spot/service/auth/AuthService.java
- src/main/java/com/example/spot/service/auth/AuthServiceImpl.java
- src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
- src/main/java/com/example/spot/web/controller/AuthController.java
- src/main/java/com/example/spot/web/controller/SearchController.java
- src/main/java/com/example/spot/web/dto/member/MemberRequestDTO.java
- src/main/java/com/example/spot/web/dto/member/MemberResponseDTO.java
- src/main/java/com/example/spot/web/dto/search/BaseSearchRequestStudyDTO.java
- src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
#411
<br/>
1. 내 관심 지역, 관심 분야, 모집 중 스터디 조회 시, 활동비를 최댓값만 입력 받는게 아닌, 범위로 필터링 할 수 있도록 로직 확장
<br/>
> 
<br/>
> [FEAT] 스터디 조회 시 활동비 필터링을 단일값에서 범위 조건으로 확장

- src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
- src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
- src/main/java/com/example/spot/web/dto/search/BaseSearchRequestStudyDTO.java
#416 
<br/>
- 입력되지 않은 필터 조건은 검색에 반영되지 않도록 수정 
-  아무 조건도 입력하지 않아도 검색 가능
- 오프라인 선택 시, 지역 코드 필수적으로 입력하도록 구현
- 필터링 조건 생성 로직 
- 중복되는 로직은 메서드 분리 진행 
<br/>
> 
<br/>
> [MODIFY] 스터디 검색 필터링 조건 관련 개선

- src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
- src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
- src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
- src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
#419 
<br/>
- Before : 스터디 활성화 유무에 관계 없이 조회 한 뒤, 활성화 된 스터디 필터링 
- After : 조회할 때 부터 활성화 된 스터디만 조회 하도록 수정
<br/>
> 
<br/>
> [MODIFY] 참여중인 스터디 조회 쿼리 수정 

- src/main/java/com/example/spot/domain/mapping/MemberStudy.java
- src/main/java/com/example/spot/domain/study/Study.java
- src/main/java/com/example/spot/repository/MemberStudyRepository.java
- src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
- src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
- src/main/java/com/example/spot/service/memberstudy/MemberStudyCommandServiceImpl.java
- src/main/java/com/example/spot/service/study/StudyCommandServiceImpl.java
- src/main/java/com/example/spot/service/study/StudyQueryService.java
- src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
- src/main/java/com/example/spot/web/controller/SearchController.java
- src/main/java/com/example/spot/web/dto/search/StudyHistoryResponseDTO.java
- #425 
<br/>
- `MemberStudy`에 종료 시간, 상태 컬럼 추가
- 스터디 히스토리 조회 API 구현
<br/>
> 
<br/>
> [FEAT] 스터디 히스토리 조회 API 구현

- src/main/java/com/example/spot/repository/querydsl/StudyRepositoryCustom.java
- src/main/java/com/example/spot/repository/querydsl/impl/StudyRepositoryCustomImpl.java
- src/main/java/com/example/spot/service/study/StudyQueryServiceImpl.java
- src/test/java/com/example/spot/service/study/StudyQueryServiceTest.java
- #428 
- SPOT-290
<br/>
오랜만이에요! 제가 생각없이 일을 이것저것 너무 벌려놔서 스팟에 신경을 많이 못쓰고 있군요... 미안해여... 그래도 조만간 다시 열심히 작업해볼게요!
- 모집 중 스터디 조회 시, 응답 DTO 내 페이지 갯수와 실제 데이터 불일치 해결
<br/>
> 
<br/>
> [REFACTOR] 모집 중 스터디 조회 시, 응답 DTO 내 페이지 갯수와 실제 데이터 불일치 해결
